import { RunAudit } from './runAudit';
import type { CatalogueCourse } from '../types/courseCatalogue'
import type { CourseAttempt } from '../types/coursePlan'
import type { StudentSetupProfile } from '../types/studentProfile'

const classifiedCourses: CatalogueCourse[] = [
  {
    course_code: 'CHEM121',
    display_code: 'CHEM 121',
    subject: 'CHEM',
    course_number: '121',
    course_level: 100,
    course_title: 'Structure and Bonding in Chemistry',
    credits: 4,
    terms_offered: ['Winter Term 1'],
    prerequisite_text: '',
    corequisite_text: '',
    prerequisites: [],
    corequisites: [],
    is_science_credit: true,
    is_arts_credit: false,
    is_upper_level: false,
    breadth_categories: ['Physical Sciences'],
    classification_notes: ['Laboratory course'],
  },
  {
    course_code: 'CHEM123',
    display_code: 'CHEM 123',
    subject: 'CHEM',
    course_number: '123',
    course_level: 100,
    course_title: 'Thermodynamics and Kinetics',
    credits: 4,
    terms_offered: ['Winter Term 2'],
    prerequisite_text: '',
    corequisite_text: '',
    prerequisites: [],
    corequisites: [],
    is_science_credit: true,
    is_arts_credit: false,
    is_upper_level: false,
    breadth_categories: ['Physical Sciences'],
    classification_notes: [],
  },
  {
    course_code: 'MATH100',
    display_code: 'MATH 100',
    subject: 'MATH',
    course_number: '100',
    course_level: 100,
    course_title: 'Differential Calculus',
    credits: 3,
    terms_offered: ['Winter Term 1'],
    prerequisite_text: '',
    corequisite_text: '',
    prerequisites: [],
    corequisites: [],
    is_science_credit: true,
    is_arts_credit: false,
    is_upper_level: false,
    breadth_categories: ['Mathematical Sciences'],
    classification_notes: [],
  },
  {
    course_code: 'MATH101',
    display_code: 'MATH 101',
    subject: 'MATH',
    course_number: '101',
    course_level: 100,
    course_title: 'Integral Calculus',
    credits: 3,
    terms_offered: ['Winter Term 2'],
    prerequisite_text: 'MATH 100',
    corequisite_text: '',
    prerequisites: ['MATH100'],
    corequisites: [],
    is_science_credit: true,
    is_arts_credit: false,
    is_upper_level: false,
    breadth_categories: ['Mathematical Sciences'],
    classification_notes: [],
  },
  {
    course_code: 'PHYS101',
    display_code: 'PHYS 101',
    subject: 'PHYS',
    course_number: '101',
    course_level: 100,
    course_title: 'Energy and Waves',
    credits: 3,
    terms_offered: ['Winter Term 1'],
    prerequisite_text: '',
    corequisite_text: '',
    prerequisites: [],
    corequisites: [],
    is_science_credit: true,
    is_arts_credit: false,
    is_upper_level: false,
    breadth_categories: ['Physical Sciences'],
    classification_notes: ['Laboratory course'],
  },
  {
    course_code: 'SCIE113',
    display_code: 'SCIE 113',
    subject: 'SCIE',
    course_number: '113',
    course_level: 100,
    course_title: 'First Year Seminar',
    credits: 3,
    terms_offered: ['Winter Term 1'],
    prerequisite_text: '',
    corequisite_text: '',
    prerequisites: [],
    corequisites: [],
    is_science_credit: true,
    is_arts_credit: false,
    is_upper_level: false,
    breadth_categories: ['General Science'],
    classification_notes: ['Communication requirement'],
  },
  {
    course_code: 'ENGL110',
    display_code: 'ENGL 110',
    subject: 'ENGL',
    course_number: '110',
    course_level: 100,
    course_title: 'Writing and Research',
    credits: 3,
    terms_offered: ['Winter Term 2'],
    prerequisite_text: '',
    corequisite_text: '',
    prerequisites: [],
    corequisites: [],
    is_science_credit: false,
    is_arts_credit: true,
    is_upper_level: false,
    breadth_categories: [],
    classification_notes: ['Communication requirement'],
  },
  {
    course_code: 'CHEM233',
    display_code: 'CHEM 233',
    subject: 'CHEM',
    course_number: '233',
    course_level: 200,
    course_title: 'Organic Chemistry I',
    credits: 4,
    terms_offered: ['Winter Term 1'],
    prerequisite_text: 'CHEM 123',
    corequisite_text: '',
    prerequisites: ['CHEM123'],
    corequisites: [],
    is_science_credit: true,
    is_arts_credit: false,
    is_upper_level: false,
    breadth_categories: ['Physical Sciences'],
    classification_notes: [],
  },
  {
    course_code: 'CHEM235',
    display_code: 'CHEM 235',
    subject: 'CHEM',
    course_number: '235',
    course_level: 200,
    course_title: 'Organic Chemistry II',
    credits: 4,
    terms_offered: ['Winter Term 2'],
    prerequisite_text: 'CHEM 233',
    corequisite_text: '',
    prerequisites: ['CHEM233'],
    corequisites: [],
    is_science_credit: true,
    is_arts_credit: false,
    is_upper_level: false,
    breadth_categories: ['Physical Sciences'],
    classification_notes: [],
  },
  {
    course_code: 'CHEM313',
    display_code: 'CHEM 313',
    subject: 'CHEM',
    course_number: '313',
    course_level: 300,
    course_title: 'Advanced Physical Chemistry',
    credits: 3,
    terms_offered: ['Winter Term 1'],
    prerequisite_text: 'CHEM 233',
    corequisite_text: '',
    prerequisites: ['CHEM233'],
    corequisites: [],
    is_science_credit: true,
    is_arts_credit: false,
    is_upper_level: true,
    breadth_categories: ['Physical Sciences'],
    classification_notes: ['Upper-level science credit'],
  },
  {
    course_code: 'CHEM315',
    display_code: 'CHEM 315',
    subject: 'CHEM',
    course_number: '315',
    course_level: 300,
    course_title: 'Inorganic Chemistry',
    credits: 3,
    terms_offered: ['Winter Term 2'],
    prerequisite_text: 'CHEM 233',
    corequisite_text: '',
    prerequisites: ['CHEM233'],
    corequisites: [],
    is_science_credit: true,
    is_arts_credit: false,
    is_upper_level: true,
    breadth_categories: ['Physical Sciences'],
    classification_notes: ['Upper-level science credit'],
  },
];

const studentCoursePlan: CourseAttempt[] = [
  {
    attempt_id: '1',
    course_code: 'CHEM121',
    display_code: 'CHEM 121',
    subject: 'CHEM',
    course_number: '121',
    course_level: 100,
    course_title: 'Structure and Bonding in Chemistry',
    credits: 4,
    status: 'completed',
    grade: 'P',
    percentage: 78,
    year_taken: 1,
    term_taken: 'winter_1',
    is_science_credit: true,
    is_arts_credit: false,
    is_upper_level: false,
    source: 'manual',
  },
  {
    attempt_id: '2',
    course_code: 'CHEM123',
    display_code: 'CHEM 123',
    subject: 'CHEM',
    course_number: '123',
    course_level: 100,
    course_title: 'Thermodynamics and Kinetics',
    credits: 4,
    status: 'completed',
    grade: 'P',
    percentage: 82,
    year_taken: 1,
    term_taken: 'winter_2',
    is_science_credit: true,
    is_arts_credit: false,
    is_upper_level: false,
    source: 'manual',
  },
  {
    attempt_id: '3',
    course_code: 'MATH100',
    display_code: 'MATH 100',
    subject: 'MATH',
    course_number: '100',
    course_level: 100,
    course_title: 'Differential Calculus',
    credits: 3,
    status: 'completed',
    grade: 'P',
    percentage: 75,
    year_taken: 1,
    term_taken: 'winter_1',
    is_science_credit: true,
    is_arts_credit: false,
    is_upper_level: false,
    source: 'manual',
  },
  {
    attempt_id: '4',
    course_code: 'MATH101',
    display_code: 'MATH 101',
    subject: 'MATH',
    course_number: '101',
    course_level: 100,
    course_title: 'Integral Calculus',
    credits: 3,
    status: 'completed',
    grade: 'P',
    percentage: 79,
    year_taken: 1,
    term_taken: 'winter_2',
    is_science_credit: true,
    is_arts_credit: false,
    is_upper_level: false,
    source: 'manual',
  },
  {
    attempt_id: '5',
    course_code: 'PHYS101',
    display_code: 'PHYS 101',
    subject: 'PHYS',
    course_number: '101',
    course_level: 100,
    course_title: 'Energy and Waves',
    credits: 3,
    status: 'completed',
    grade: 'P',
    percentage: 71,
    year_taken: 1,
    term_taken: 'winter_1',
    is_science_credit: true,
    is_arts_credit: false,
    is_upper_level: false,
    source: 'manual',
  },
  {
    attempt_id: '6',
    course_code: 'SCIE113',
    display_code: 'SCIE 113',
    subject: 'SCIE',
    course_number: '113',
    course_level: 100,
    course_title: 'First Year Seminar',
    credits: 3,
    status: 'completed',
    grade: 'P',
    percentage: 88,
    year_taken: 1,
    term_taken: 'winter_1',
    is_science_credit: true,
    is_arts_credit: false,
    is_upper_level: false,
    source: 'manual',
  },
  {
    attempt_id: '7',
    course_code: 'ENGL110',
    display_code: 'ENGL 110',
    subject: 'ENGL',
    course_number: '110',
    course_level: 100,
    course_title: 'Writing and Research',
    credits: 3,
    status: 'completed',
    grade: 'P',
    percentage: 84,
    year_taken: 1,
    term_taken: 'winter_2',
    is_science_credit: false,
    is_arts_credit: true,
    is_upper_level: false,
    source: 'manual',
  },
  {
    attempt_id: '8',
    course_code: 'CHEM233',
    display_code: 'CHEM 233',
    subject: 'CHEM',
    course_number: '233',
    course_level: 200,
    course_title: 'Organic Chemistry I',
    credits: 4,
    status: 'completed',
    grade: 'P',
    percentage: 76,
    year_taken: 2,
    term_taken: 'winter_1',
    is_science_credit: true,
    is_arts_credit: false,
    is_upper_level: false,
    source: 'manual',
  },
  {
    attempt_id: '9',
    course_code: 'CHEM235',
    display_code: 'CHEM 235',
    subject: 'CHEM',
    course_number: '235',
    course_level: 200,
    course_title: 'Organic Chemistry II',
    credits: 4,
    status: 'completed',
    grade: 'P',
    percentage: 73,
    year_taken: 2,
    term_taken: 'winter_2',
    is_science_credit: true,
    is_arts_credit: false,
    is_upper_level: false,
    source: 'manual',
  },
  {
    attempt_id: '10',
    course_code: 'CHEM313',
    display_code: 'CHEM 313',
    subject: 'CHEM',
    course_number: '313',
    course_level: 300,
    course_title: 'Advanced Physical Chemistry',
    credits: 3,
    status: 'completed',
    grade: 'P',
    percentage: 80,
    year_taken: 3,
    term_taken: 'winter_1',
    is_science_credit: true,
    is_arts_credit: false,
    is_upper_level: true,
    source: 'manual',
  },
  {
    attempt_id: '11',
    course_code: 'CHEM315',
    display_code: 'CHEM 315',
    subject: 'CHEM',
    course_number: '315',
    course_level: 300,
    course_title: 'Inorganic Chemistry',
    credits: 3,
    status: 'in_progress',
    grade: '',
    percentage: null,
    year_taken: 3,
    term_taken: 'winter_2',
    is_science_credit: true,
    is_arts_credit: false,
    is_upper_level: true,
    source: 'manual',
  },
];

const studentProfile: StudentSetupProfile = {
    calendar_year: '2026-2027',
    program: 'ENSC',
    program_type: 'Major',
    option_id: '',
    academic_year: 4,
};

const result = RunAudit({
    classified_courses: classifiedCourses,
    student_course_plan: studentCoursePlan,
    student_profile: studentProfile,
});

console.log(
    JSON.stringify(result, null, 2)
);